site_name: SNAPISTA

theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - mkdocs-jupyter

nav:
  - Introduction: 'index.md'
  - Installation: 'installation.md'
  - Getting started: 'gettingstarted.md'
  - Examples: 
    - Operator: examples/operator.ipynb
    - Graph: examples/graph.ipynb
    - BandMaths: examples/bandmaths.ipynb
    - SAR calibration: examples/sar-calibration.ipynb
