site_name: SNAPISTA

theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Introduction: 'index.md'
  - Installation: 'installation.md'
  - Getting started: 'gettingstarted.md'
  - Examples: 'examples.md'