{% set data = load_setup_py_data() %}

package:
  name: snapista
  version: {{ data.get('version') }}

source:
  path: ..

build:

  number: 2

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - lxml
    - psutil
    - snap=8.0.0

test:

  imports:
    - lxml
    - snapista
    
  commands:

  requires:
    - lxml
    - psutil
    - snap=8.0.0

about:
  home: http://project.terradue.com/
  license: EUPL License
  summary: "Helpers for SNAP and Python"

