package:
  name: snapista
  version: "0.0.1"

source:
  path: ..

build:

  number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - lxml
    - psutil
    - snap=8.0.0

test:
  # Python imports
  imports:
    - lxml
    - snapista
    
  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.
    #test_cioppy.py

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    # Put any additional test requirements here.  For example
    - lxml
    - psutil
    - snap=8.0.0

about:
  home: http://project.terradue.com/
  license: EUPL License
  summary: "Helpers for SNAP and Python"

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
