{% set data = load_setup_py_data() %}

package:
  name: snapista
  version: {{ data.get('version') }}

source:
  path: ..

build:

  number: 3

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - lxml
    - psutil
    - snap >=8.0.0
    - attrs

test:

  imports:
    - lxml
    - snapista
    - attr
    
  commands:

  requires:
    - lxml
    - psutil
    - snap >=8.0.0
    - attrs

about:
  home: https://github.com/snap-contrib/snapista
  license: MIT
  summary: "SNAP GPT Python wrapper"

